
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author MARIA ROSALES ROMAN
 */
public class Formulario extends javax.swing.JDialog {

    /**
     * Creates new form Dialogo
     *
     * @param parent
     * @param modal
     */
    public Formulario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guardar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dni = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        isbn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        titulo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        autor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        editorial = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        encuadernacion = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        materias = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        topics = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        prestamo = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        entrega = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        guardar.setText("Guardar registro");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("FORMULARIO PARA LA RECOGIDA DE DATOS DEL PRÉSTAMO  ");

        jPanel1.setLayout(new java.awt.GridLayout(12, 2));

        jLabel1.setText("Nombre y apellidos");
        jPanel1.add(jLabel1);

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreKeyTyped(evt);
            }
        });
        jPanel1.add(nombre);

        jLabel3.setText("Teléfono");
        jPanel1.add(jLabel3);

        telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonoKeyTyped(evt);
            }
        });
        jPanel1.add(telefono);

        jLabel2.setText("DNI");
        jPanel1.add(jLabel2);

        dni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dniKeyTyped(evt);
            }
        });
        jPanel1.add(dni);

        jLabel4.setText("ISBN");
        jPanel1.add(jLabel4);

        isbn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                isbnKeyTyped(evt);
            }
        });
        jPanel1.add(isbn);

        jLabel5.setText("Título del libro");
        jPanel1.add(jLabel5);

        titulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tituloKeyTyped(evt);
            }
        });
        jPanel1.add(titulo);

        jLabel6.setText("Autor");
        jPanel1.add(jLabel6);

        autor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                autorKeyTyped(evt);
            }
        });
        jPanel1.add(autor);

        jLabel7.setText("Editorial");
        jPanel1.add(jLabel7);

        editorial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Urano Ediciones", "Círculo rojo", "Vicens Vives", "Altamar" }));
        editorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editorialActionPerformed(evt);
            }
        });
        jPanel1.add(editorial);

        jLabel8.setText("Tipo de encuadernación");
        jPanel1.add(jLabel8);

        encuadernacion.setEnabled(false);
        encuadernacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                encuadernacionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                encuadernacionFocusLost(evt);
            }
        });
        encuadernacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encuadernacionActionPerformed(evt);
            }
        });
        jPanel1.add(encuadernacion);

        jLabel9.setText("Materias");
        jPanel1.add(jLabel9);

        materias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alimentación-Nutrición", "Medicina", "Derecho", "Música" }));
        materias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materiasActionPerformed(evt);
            }
        });
        jPanel1.add(materias);

        jLabel13.setText("Topics");
        jPanel1.add(jLabel13);

        topics.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Análisis de alimentos", "Industria alimentaria", "Nutrición y dietética" }));
        jPanel1.add(topics);

        jLabel10.setText("Fecha de préstamo");
        jPanel1.add(jLabel10);

        prestamo.setModel(new javax.swing.SpinnerDateModel());
        prestamo.setEditor(new javax.swing.JSpinner.DateEditor(prestamo, "dd.MM.yyyy"));
        jPanel1.add(prestamo);

        jLabel11.setText("Fecha de entrega");
        jPanel1.add(jLabel11);

        entrega.setModel(new javax.swing.SpinnerDateModel());
        entrega.setEditor(new javax.swing.JSpinner.DateEditor(entrega, "dd.MM.yyyy"));
        jPanel1.add(entrega);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(guardar)
                        .addGap(60, 60, 60)
                        .addComponent(salir)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardar)
                    .addComponent(salir))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // comprueba si el campo esta vacio y lo marca en rojo. Devuelve false si esta vacio
    private boolean campoVacio(JTextField campo) {
        if (campo.getText().isEmpty()) {
            campo.setBackground(Color.red);
            return true;
        } else {
            campo.setBackground(Color.white);
        }
        return false;
    }

    // BOTON DE GUARDAR
    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed

        // comprueba si hay algun campo vacio
        if (campoVacio(nombre)
                || campoVacio(telefono)
                || campoVacio(dni)
                || campoVacio(isbn)
                || campoVacio(autor)
                || campoVacio(titulo)) {

        } else {
            // si están todos los campos, se crea un objeto registro con los datos
            Registro registroNuevo = new Registro(nombre.getText(), telefono.getText(), dni.getText(),
                    isbn.getText(), titulo.getText(), autor.getText(),
                    editorial.getSelectedItem().toString(), encuadernacion.getSelectedItem().toString(),
                    materias.getSelectedItem().toString(), topics.getSelectedItem().toString(),
                    prestamo.getValue().toString(), entrega.getValue().toString());

            // muestra mensaje de que se ha guardado y cierra la ventana
            JOptionPane.showMessageDialog(this,
                    "¡Datos guardados correctamente!",
                    "Guardar",
                    JOptionPane.INFORMATION_MESSAGE);
            dispose();
        }

    }//GEN-LAST:event_guardarActionPerformed

    // BOTON DE SALIR
    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // si no ha rellenado ningun campo, sale directamente
        if (campoVacio(nombre)
                && campoVacio(telefono)
                && campoVacio(dni)
                && campoVacio(isbn)
                && campoVacio(autor)
                && campoVacio(titulo)) {
            dispose();
        } else {
            // si hay algun campo relleno, pregunta por confirmacion
            int respuesta = JOptionPane.showConfirmDialog(null, "Realmente desea salir?", "Confirmar salida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (respuesta == JOptionPane.YES_OPTION) {
                dispose();
            }
        }

    }//GEN-LAST:event_salirActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    
    // DEFINIENDO TAMAÑO MÁXIMO DE LAS ENTRADAS
    private void nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyTyped
        if (nombre.getText().length() >= 30) {
            evt.consume();
        }
    }//GEN-LAST:event_nombreKeyTyped

    private void telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoKeyTyped
        if (telefono.getText().length() >= 9) {
            evt.consume();
        }
    }//GEN-LAST:event_telefonoKeyTyped

    private void dniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dniKeyTyped
        if (dni.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_dniKeyTyped

    private void isbnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isbnKeyTyped
        if (isbn.getText().length() >= 13) {
            evt.consume();
        }
    }//GEN-LAST:event_isbnKeyTyped

    private void tituloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tituloKeyTyped
        if (titulo.getText().length() >= 30) {
            evt.consume();
        }
    }//GEN-LAST:event_tituloKeyTyped

    private void autorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_autorKeyTyped
        if (autor.getText().length() >= 20) {
            evt.consume();
        }
    }//GEN-LAST:event_autorKeyTyped

    private void encuadernacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encuadernacionActionPerformed

    }//GEN-LAST:event_encuadernacionActionPerformed

    private void encuadernacionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_encuadernacionFocusGained


    }//GEN-LAST:event_encuadernacionFocusGained

    private void encuadernacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_encuadernacionFocusLost

    }//GEN-LAST:event_encuadernacionFocusLost

    private void editorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editorialActionPerformed
        //Sólo se permitirá elegir el tipo de encuadernación en el caso de que para la 
        //Editorial se haya elegido "Círculo rojo" o "Vincens Vives". 
        //En cualquier otro caso, no se podrá seleccionar el tipo de encuadernación.
        //Entre los tipos de encuadernación podremos seleccionar "Rústica", "Tapa dura" o "Piel".
        
        // si la editorial es "Círculo rojo" (1) o "Vincens Vives" (2) se añaden el tipo de encuadernacion
        if (editorial.getSelectedIndex() == 1 | editorial.getSelectedIndex() == 2) {
            encuadernacion.setEnabled(true);
            encuadernacion.addItem("Rústica");
            encuadernacion.addItem("Tapa Dura");
            encuadernacion.addItem("Piel");
        } else {
            // en las otras editoriales se borran los elementos de la encuadernacion y se deshabilita
            encuadernacion.removeAllItems();
            encuadernacion.setEnabled(false);
        }
    }//GEN-LAST:event_editorialActionPerformed

    private void materiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materiasActionPerformed
//        Materias: Se podrá elegir entre las siguientes materias ”Alimentación-Nutrición”,” Medicina”, “Derecho” y "Música”. Así, dependiendo de la materia elegida, se podrá elegir una o más de una de entre las siguientes topics:
//En la materia “Alimentación-Nutrición”, se podrá elegir una o más de los siguientes topics: "Análisis de alimentos”, “Industria alimentaria”, “Nutrición y dietética”.
//En la materia “Medicina”,se podrá elegir una o más de una de entre los siguientes topics: “Neurología”, “Patología”, “Medicina general”.
//En la materia “Derecho”, se podrá elegir una o más de una de entre los siguientes topics: “Derecho privado”, “Derecho público”, “Derecho militar”.
//En la materia “Música”, se podrá elegir una o más de una de entre los siguientes topics: “Flamenco”, “Música clásica”, “Teoría e historia de la música”.

// segun la materia elegida, añade los topics (antes de añadir, borra para formatear los elementos)
        switch (materias.getSelectedIndex()) {
            case 0 -> {
                topics.removeAllItems();
                topics.addItem("Análisis de alimentos");
                topics.addItem("Industria alimentaria");
                topics.addItem("Nutrición y dietética");
                break;
            }
            case 1 -> {
                topics.removeAllItems();
                topics.addItem("Neurología");
                topics.addItem("Patología");
                topics.addItem("Medicina general");
                break;
            }
            case 2 -> {
                topics.removeAllItems();
                topics.addItem("Derecho privado");
                topics.addItem("Derecho público");
                topics.addItem("Derecho militar");
                break;
            }
            case 3 -> {
                topics.removeAllItems();
                topics.addItem("Flamenco");
                topics.addItem("Música clásica");
                topics.addItem("Teoría e historia de la música");
                break;
            }
        }

    }//GEN-LAST:event_materiasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Formulario dialog = new Formulario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField autor;
    private javax.swing.JTextField dni;
    private javax.swing.JComboBox<String> editorial;
    private javax.swing.JComboBox<String> encuadernacion;
    private javax.swing.JSpinner entrega;
    private javax.swing.JButton guardar;
    private javax.swing.JTextField isbn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> materias;
    private javax.swing.JTextField nombre;
    private javax.swing.JSpinner prestamo;
    private javax.swing.JButton salir;
    private javax.swing.JTextField telefono;
    private javax.swing.JTextField titulo;
    private javax.swing.JComboBox<String> topics;
    // End of variables declaration//GEN-END:variables
}
